export const initialVals = {
    first_name:  "",
    last_name:  "",
    email: "",
    phone: "",
    mobile:  "",
    post_code:  "",
    business_name: "",
    business_hrs: null, 
    nif:  "",
    mgr_name:  "",
    address:  "",
    longitude: null,
    latitude: null,
    account_hldr_name: "",
    bank_name: "",
    incharge_staff: "",
    notes: "",
    iban: "",
    category_id:null,
    license_img : null,
  };